### ISSUE TITLE
Combining Patch Collections

### ISSUE THREAD

**Issue by nodediggity** [peterringset/JSONPatch#2]
Hey, 

Awesome library however I'm a little confused -

In the docs you have `stringChanges` and `arrayChanges` but in the next step of the example you have `let data = try! encoder.encode(changes)`.

The example output is a single, complete JSON patch.

What is `changes` and how did you get to this from `stringChanges` and `arrayChanges` please?

At the moment I am essentially ending up with 2 difference collections that cannot be merged as they contain different types?

Thank you!

**Comment by peterringset** [comment]
Hi, thanks for your comment!

You're completely right, it's not possible to combine the two arrays, since they have different types for the value.

I realised that this was not a very user friendly API, so I've made a new implementation of this library and released it as version 2.0. In the new version I've changed the signature of the JSONPatch type so that it's only generic is the type of the receiver. This way you can combine properties that have different types into one array.

Check the current README for this repo for more details. Hope this helps.
